CREATE TABLE xml_store (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR2(255),
    uploaded_by VARCHAR2(100),
    uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    xml_content CLOB
);

COMMIT;
-- Privilegios: asegúrese de que el usuario tenga INSERT/SELECT en la tabla